name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  storybook:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
    - run: bun install
    - run: npx storybook build -o ./build_storybook 
    - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${{github.repository}}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "arturia-storybook.ameliart.fr" > ./build_storybook/CNAME
    - run: npx -y -p gh-pages@3.1.0 gh-pages -d ./build_storybook -u "github-actions-bot <actions@github.com>" 
